module.exports = {
  apps: [
    {
      name: 'traderr',
      script: './start-traderr.sh',
      cwd: __dirname,
      interpreter: '/bin/bash',
      autorestart: true,
      restart_delay: 5000,
      exp_backoff_restart_delay: 2000,
      max_restarts: 100,
      watch: false,
      max_memory_restart: '800M',
      out_file: './logs/bot-out.log',
      error_file: './logs/bot-err.log',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOST: '0.0.0.0',
        AUTOSTART: 'true',
        ALLOW_IN_MEMORY_STORE: 'true',
        EXCHANGE_VENUE: process.env.EXCHANGE_VENUE || 'hyperliquid',
        LIVE_TRADING_ENABLED: process.env.LIVE_TRADING_ENABLED || 'false',
        HYPERLIQUID_WALLET: process.env.HYPERLIQUID_WALLET || '',
        HYPERLIQUID_PRIVATE_KEY: process.env.HYPERLIQUID_PRIVATE_KEY || '',
        HYPERLIQUID_TESTNET: process.env.HYPERLIQUID_TESTNET || 'false',
      },
    },
  ],
};
